apiVersion: v1
kind: Service
metadata:
  name: logo-server-service
spec:
  selector:
    app: logo-server
  ports:
    - protocol: TCP
      port: 80          # Public port
      targetPort: 3000  # Pod container port
      nodePort: 32000
  type: NodePort

